// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 68wGqrWvUbUk9uG76N3xHk
// Component: t5yBiOJTZxA
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Checkbox from "../../Checkbox"; // plasmic-import: NK-xeF1iGEb/component
import TextInput from "../../TextInput"; // plasmic-import: UzcYFC-NJii/component
import Button from "../../Button"; // plasmic-import: UCG438gq_ly/component
import Timeline from "../../Timeline"; // plasmic-import: 0RHyvgnmPT/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "../blank_project/plasmic_blank_project.module.css"; // plasmic-import: 68wGqrWvUbUk9uG76N3xHk/projectcss
import sty from "./PlasmicChoosePasses.module.css"; // plasmic-import: t5yBiOJTZxA/css
import WizardSvgrepoComsvg2Icon from "../blank_project/icons/PlasmicIcon__WizardSvgrepoComsvg2"; // plasmic-import: ppcK-LiUA7/icon
import screenShot20220619At70250PMpngCyEWdgYSm from "../blank_project/images/screenShot20220619At70250PMpng.png"; // plasmic-import: cyEWdgYSm/picture

export const PlasmicChoosePasses__VariantProps = new Array();

export const PlasmicChoosePasses__ArgProps = new Array();

export const defaultChoosePasses__Args = {};

function PlasmicChoosePasses__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultChoosePasses__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox__fJp20)} />
          ) : null}

          <div
            data-plasmic-name={"columns"}
            data-plasmic-override={overrides.columns}
            className={classNames(projectcss.all, sty.columns)}
          >
            <div className={classNames(projectcss.all, sty.column__eEAqS)}>
              <div className={classNames(projectcss.all, sty.freeBox__fdw4K)}>
                <div className={classNames(projectcss.all, sty.freeBox__nK4Bp)}>
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"Choose Your Passes"}
                  </h1>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dXhnB
                    )}
                  >
                    {"Select the types of passes you would like to use."}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox___5Ldzc)}
                  >
                    <Checkbox
                      className={classNames(
                        "__wab_instance",
                        sty.checkbox___0SfM
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zbwQs
                        )}
                      >
                        {"Day Pass"}
                      </div>
                    </Checkbox>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lIYzR
                      )}
                    >
                      {"Price:"}
                    </div>

                    <TextInput
                      className={classNames(
                        "__wab_instance",
                        sty.textInput__fcJse
                      )}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__q7U8I
                      )}
                    >
                      {"Tezos"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zzjlJ
                      )}
                    >
                      {"or"}
                    </div>

                    <TextInput
                      className={classNames(
                        "__wab_instance",
                        sty.textInput___3AFcp
                      )}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__guq11
                      )}
                    >
                      {"Dollars"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uUYw
                      )}
                    >
                      {
                        "Day Pass Allows User Access for 24 hours from time of purchase."
                      }
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__gfUiO)}
                  >
                    <Checkbox
                      className={classNames(
                        "__wab_instance",
                        sty.checkbox__ypLy
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__elT4R
                        )}
                      >
                        {"Weekly  Pass"}
                      </div>
                    </Checkbox>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bOWot
                      )}
                    >
                      {"Price:"}
                    </div>

                    <TextInput
                      className={classNames(
                        "__wab_instance",
                        sty.textInput__i9JYj
                      )}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hvDy
                      )}
                    >
                      {"Tezos"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sfZrs
                      )}
                    >
                      {"or"}
                    </div>

                    <TextInput
                      className={classNames(
                        "__wab_instance",
                        sty.textInput__k6VqD
                      )}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ukg2K
                      )}
                    >
                      {"Dollars"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0VX
                      )}
                    >
                      {
                        "Weekly  Pass Allows User Access for 7 Days from time of purchase."
                      }
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__gbSc)}
                  >
                    <Checkbox
                      className={classNames(
                        "__wab_instance",
                        sty.checkbox__ewUk
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ljT0L
                        )}
                      >
                        {"Yearly Pass"}
                      </div>
                    </Checkbox>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rPh7Q
                      )}
                    >
                      {"Price:"}
                    </div>

                    <TextInput
                      className={classNames(
                        "__wab_instance",
                        sty.textInput__yaGdR
                      )}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pe1Xl
                      )}
                    >
                      {"Tezos"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0JpD
                      )}
                    >
                      {"or"}
                    </div>

                    <TextInput
                      className={classNames(
                        "__wab_instance",
                        sty.textInput___25YhH
                      )}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__y8CaY
                      )}
                    >
                      {"Dollars"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lic6Z
                      )}
                    >
                      {
                        "Weekly  Pass Allows User Access for 365 Days from time of purchase."
                      }
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__mZxa)}
                  >
                    <Checkbox
                      className={classNames(
                        "__wab_instance",
                        sty.checkbox__r8Gwr
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4HmTn
                        )}
                      >
                        {"Special Event Pass"}
                      </div>
                    </Checkbox>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1FnOq
                      )}
                    >
                      {"Price:"}
                    </div>

                    <TextInput
                      className={classNames(
                        "__wab_instance",
                        sty.textInput__dmvNl
                      )}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tPf1Y
                      )}
                    >
                      {"Tezos"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__a99W
                      )}
                    >
                      {"or"}
                    </div>

                    <TextInput
                      className={classNames(
                        "__wab_instance",
                        sty.textInput__mSayv
                      )}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nBeXi
                      )}
                    >
                      {"Dollars"}
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ia94W
                      )}
                    >
                      {
                        "Special Event Pass Allows User Access to a single event."
                      }
                    </div>
                  </div>
                </div>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xGnNx)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__pgxTa)}
                  />

                  <Button
                    data-plasmic-name={"backButton"}
                    data-plasmic-override={overrides.backButton}
                    className={classNames("__wab_instance", sty.backButton)}
                  >
                    {"Back"}
                  </Button>

                  <Button
                    data-plasmic-name={"nextButton"}
                    data-plasmic-override={overrides.nextButton}
                    className={classNames("__wab_instance", sty.nextButton)}
                  >
                    {"Next"}
                  </Button>
                </p.Stack>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column__uUAkl)}>
              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__fBvVl)}>
                  <WizardSvgrepoComsvg2Icon
                    data-plasmic-name={"svg"}
                    data-plasmic-override={overrides.svg}
                    className={classNames(projectcss.all, sty.svg)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ceZ4H
                    )}
                  >
                    {"AccTez Wizard"}
                  </div>

                  <p.PlasmicImg
                    data-plasmic-name={"img"}
                    data-plasmic-override={overrides.img}
                    alt={""}
                    className={classNames(sty.img)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: screenShot20220619At70250PMpngCyEWdgYSm,
                      fullWidth: 627,
                      fullHeight: 419,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              ) : null}

              <Timeline
                data-plasmic-name={"timeline"}
                data-plasmic-override={overrides.timeline}
                className={classNames("__wab_instance", sty.timeline)}
              />
            </div>
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "columns",
    "h1",
    "backButton",
    "nextButton",
    "svg",
    "img",
    "timeline"
  ],

  columns: [
    "columns",
    "h1",
    "backButton",
    "nextButton",
    "svg",
    "img",
    "timeline"
  ],

  h1: ["h1"],
  backButton: ["backButton"],
  nextButton: ["nextButton"],
  svg: ["svg"],
  img: ["img"],
  timeline: ["timeline"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicChoosePasses__ArgProps,
      internalVariantPropNames: PlasmicChoosePasses__VariantProps
    });

    return PlasmicChoosePasses__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicChoosePasses";
  } else {
    func.displayName = `PlasmicChoosePasses.${nodeName}`;
  }
  return func;
}

export const PlasmicChoosePasses = Object.assign(
  // Top-level PlasmicChoosePasses renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),
    h1: makeNodeComponent("h1"),
    backButton: makeNodeComponent("backButton"),
    nextButton: makeNodeComponent("nextButton"),
    svg: makeNodeComponent("svg"),
    img: makeNodeComponent("img"),
    timeline: makeNodeComponent("timeline"),
    // Metadata about props expected for PlasmicChoosePasses
    internalVariantProps: PlasmicChoosePasses__VariantProps,
    internalArgProps: PlasmicChoosePasses__ArgProps
  }
);

export default PlasmicChoosePasses;
/* prettier-ignore-end */
